// Code generated by Wire protocol buffer compiler, do not edit.
// Source: protobuf.source.component.CellTextStyle in component/cell_text_style.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package protobuf.source.component

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.internal.JvmField
import com.squareup.wire.internal.JvmStatic

public enum class CellTextStyle(
  override val `value`: Int,
) : WireEnum {
  CELL_TEXT_STYLE_UNSPECIFIED(0),
  CELL_TEXT_STYLE_BOLD(1),
  CELL_TEXT_STYLE_MEDIUM(2),
  CELL_TEXT_STYLE_REGULAR(3),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CellTextStyle> = object : EnumAdapter<CellTextStyle>(
      CellTextStyle::class,
      PROTO_3,
      CellTextStyle.CELL_TEXT_STYLE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): CellTextStyle? = CellTextStyle.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): CellTextStyle? = when (`value`) {
      0 -> CELL_TEXT_STYLE_UNSPECIFIED
      1 -> CELL_TEXT_STYLE_BOLD
      2 -> CELL_TEXT_STYLE_MEDIUM
      3 -> CELL_TEXT_STYLE_REGULAR
      else -> null
    }
  }
}
