// Code generated by Wire protocol buffer compiler, do not edit.
// Source: protobuf.source.component.CellColor in component/cell_color.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package protobuf.source.component

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.internal.JvmField
import com.squareup.wire.internal.JvmStatic

public enum class CellColor(
  override val `value`: Int,
) : WireEnum {
  CELL_COLOR_UNSPECIFIED(0),
  CELL_COLOR_WHITE(1),
  CELL_COLOR_BLACK(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CellColor> = object : EnumAdapter<CellColor>(
      CellColor::class,
      PROTO_3,
      CellColor.CELL_COLOR_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): CellColor? = CellColor.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): CellColor? = when (`value`) {
      0 -> CELL_COLOR_UNSPECIFIED
      1 -> CELL_COLOR_WHITE
      2 -> CELL_COLOR_BLACK
      else -> null
    }
  }
}
