// Code generated by Wire protocol buffer compiler, do not edit.
// Source: protobuf.source.component.ComponentBase in component/component_base.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package protobuf.source.component

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString
import protobuf.source.action.Action
import protobuf.source.attributes.Attributes

public class ComponentBase(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  attributes: List<Attributes> = emptyList(),
  actions: List<Action> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ComponentBase, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "protobuf.source.attributes.Attributes#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val attributes: List<Attributes> = immutableCopyOf("attributes", attributes)

  @field:WireField(
    tag = 3,
    adapter = "protobuf.source.action.Action#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val actions: List<Action> = immutableCopyOf("actions", actions)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ComponentBase) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (attributes != other.attributes) return false
    if (actions != other.actions) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + attributes.hashCode()
      result = result * 37 + actions.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    if (attributes.isNotEmpty()) result += """attributes=$attributes"""
    if (actions.isNotEmpty()) result += """actions=$actions"""
    return result.joinToString(prefix = "ComponentBase{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    attributes: List<Attributes> = this.attributes,
    actions: List<Action> = this.actions,
    unknownFields: ByteString = this.unknownFields,
  ): ComponentBase = ComponentBase(id, attributes, actions, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ComponentBase> = object : ProtoAdapter<ComponentBase>(
      FieldEncoding.LENGTH_DELIMITED, 
      ComponentBase::class, 
      "type.googleapis.com/protobuf.source.component.ComponentBase", 
      PROTO_3, 
      null, 
      "component/component_base.proto"
    ) {
      override fun encodedSize(`value`: ComponentBase): Int {
        var size = value.unknownFields.size
        if (value.id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        }
        size += Attributes.ADAPTER.asRepeated().encodedSizeWithTag(2, value.attributes)
        size += Action.ADAPTER.asRepeated().encodedSizeWithTag(3, value.actions)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ComponentBase) {
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
        Attributes.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.attributes)
        Action.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.actions)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ComponentBase) {
        writer.writeBytes(value.unknownFields)
        Action.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.actions)
        Attributes.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.attributes)
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): ComponentBase {
        var id: String = ""
        val attributes = mutableListOf<Attributes>()
        val actions = mutableListOf<Action>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> attributes.add(Attributes.ADAPTER.decode(reader))
            3 -> actions.add(Action.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ComponentBase(
          id = id,
          attributes = attributes,
          actions = actions,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ComponentBase): ComponentBase = value.copy(
        attributes = value.attributes.redactElements(Attributes.ADAPTER),
        actions = value.actions.redactElements(Action.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
