// Code generated by Wire protocol buffer compiler, do not edit.
// Source: protobuf.source.screen.Screen in screen/screen.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package protobuf.source.screen

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString
import protobuf.source.action.Action
import protobuf.source.attributes.Attributes
import protobuf.source.section.Section

public class Screen(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  attributes: List<Attributes> = emptyList(),
  actions: List<Action> = emptyList(),
  @field:WireField(
    tag = 4,
    adapter = "protobuf.source.screen.Screen${'$'}Type#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val type: Type = Type.TYPE_UNSPECIFIED,
  sections: List<Section> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Screen, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "protobuf.source.attributes.Attributes#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val attributes: List<Attributes> = immutableCopyOf("attributes", attributes)

  @field:WireField(
    tag = 3,
    adapter = "protobuf.source.action.Action#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val actions: List<Action> = immutableCopyOf("actions", actions)

  @field:WireField(
    tag = 5,
    adapter = "protobuf.source.section.Section#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 4,
  )
  public val sections: List<Section> = immutableCopyOf("sections", sections)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Screen) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (attributes != other.attributes) return false
    if (actions != other.actions) return false
    if (type != other.type) return false
    if (sections != other.sections) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + attributes.hashCode()
      result = result * 37 + actions.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + sections.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    if (attributes.isNotEmpty()) result += """attributes=$attributes"""
    if (actions.isNotEmpty()) result += """actions=$actions"""
    result += """type=$type"""
    if (sections.isNotEmpty()) result += """sections=$sections"""
    return result.joinToString(prefix = "Screen{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    attributes: List<Attributes> = this.attributes,
    actions: List<Action> = this.actions,
    type: Type = this.type,
    sections: List<Section> = this.sections,
    unknownFields: ByteString = this.unknownFields,
  ): Screen = Screen(id, attributes, actions, type, sections, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Screen> = object : ProtoAdapter<Screen>(
      FieldEncoding.LENGTH_DELIMITED, 
      Screen::class, 
      "type.googleapis.com/protobuf.source.screen.Screen", 
      PROTO_3, 
      null, 
      "screen/screen.proto"
    ) {
      override fun encodedSize(`value`: Screen): Int {
        var size = value.unknownFields.size
        if (value.id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        }
        size += Attributes.ADAPTER.asRepeated().encodedSizeWithTag(2, value.attributes)
        size += Action.ADAPTER.asRepeated().encodedSizeWithTag(3, value.actions)
        if (value.type != protobuf.source.screen.Screen.Type.TYPE_UNSPECIFIED) {
          size += Type.ADAPTER.encodedSizeWithTag(4, value.type)
        }
        size += Section.ADAPTER.asRepeated().encodedSizeWithTag(5, value.sections)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Screen) {
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
        Attributes.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.attributes)
        Action.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.actions)
        if (value.type != protobuf.source.screen.Screen.Type.TYPE_UNSPECIFIED) {
          Type.ADAPTER.encodeWithTag(writer, 4, value.type)
        }
        Section.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.sections)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Screen) {
        writer.writeBytes(value.unknownFields)
        Section.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.sections)
        if (value.type != protobuf.source.screen.Screen.Type.TYPE_UNSPECIFIED) {
          Type.ADAPTER.encodeWithTag(writer, 4, value.type)
        }
        Action.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.actions)
        Attributes.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.attributes)
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): Screen {
        var id: String = ""
        val attributes = mutableListOf<Attributes>()
        val actions = mutableListOf<Action>()
        var type: Type = Type.TYPE_UNSPECIFIED
        val sections = mutableListOf<Section>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> attributes.add(Attributes.ADAPTER.decode(reader))
            3 -> actions.add(Action.ADAPTER.decode(reader))
            4 -> try {
              type = Type.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            5 -> sections.add(Section.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return Screen(
          id = id,
          attributes = attributes,
          actions = actions,
          type = type,
          sections = sections,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Screen): Screen = value.copy(
        attributes = value.attributes.redactElements(Attributes.ADAPTER),
        actions = value.actions.redactElements(Action.ADAPTER),
        sections = value.sections.redactElements(Section.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class Type(
    override val `value`: Int,
  ) : WireEnum {
    TYPE_UNSPECIFIED(0),
    TYPE_ROOT(1),
    TYPE_BOTTOM_SHEET(2),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Type> = object : EnumAdapter<Type>(
        Type::class, 
        PROTO_3, 
        Type.TYPE_UNSPECIFIED
      ) {
        override fun fromValue(`value`: Int): Type? = Type.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Type? = when (`value`) {
        0 -> TYPE_UNSPECIFIED
        1 -> TYPE_ROOT
        2 -> TYPE_BOTTOM_SHEET
        else -> null
      }
    }
  }
}
